// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-4iME_WtA44j9VqTUZh1zTtDWTSXHuxE',
    appId: '1:522566110362:web:c732ecd8871e934c1f2323',
    messagingSenderId: '522566110362',
    projectId: 'course-dd6fc',
    authDomain: 'course-dd6fc.firebaseapp.com',
    storageBucket: 'course-dd6fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUwX6KUdRQxGMjIQUDPwTjgbeXZjIyx6g',
    appId: '1:522566110362:android:aeac09cc639afe081f2323',
    messagingSenderId: '522566110362',
    projectId: 'course-dd6fc',
    storageBucket: 'course-dd6fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz28l7w_M_9O0-4LpvOuMo1CIsok77Q_s',
    appId: '1:522566110362:ios:5ad7678a5013df7e1f2323',
    messagingSenderId: '522566110362',
    projectId: 'course-dd6fc',
    storageBucket: 'course-dd6fc.firebasestorage.app',
    iosBundleId: 'com.example.google',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz28l7w_M_9O0-4LpvOuMo1CIsok77Q_s',
    appId: '1:522566110362:ios:5ad7678a5013df7e1f2323',
    messagingSenderId: '522566110362',
    projectId: 'course-dd6fc',
    storageBucket: 'course-dd6fc.firebasestorage.app',
    iosBundleId: 'com.example.google',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-4iME_WtA44j9VqTUZh1zTtDWTSXHuxE',
    appId: '1:522566110362:web:1ee9244f2d68d29d1f2323',
    messagingSenderId: '522566110362',
    projectId: 'course-dd6fc',
    authDomain: 'course-dd6fc.firebaseapp.com',
    storageBucket: 'course-dd6fc.firebasestorage.app',
  );
}
